### PR TITLE
linters added

### PR DESCRIPTION
**Pull request by Fikrat2002**
Screenshot 2024-07-02 204815

### CODE REVIEW

**Comment by Fikrat2002** [comment]
@far_faqiri
I would be thankful of your feedbacks

**Comment by ahzamir** [comment]
@Fikrat2002 
You mentioned your partner with the wrong username.

**Comment by ahzamir** [comment]
@Fikrat2002 

- The linter issue is that you did not add the github folder. While adding linters to your project you have to add the github folder too.

**Comment by Fikrat2002** [comment]
@ahzamir 
linters issues solved, kindly check it out

**Comment by ahzamir** [comment]
@Fikrat2002 

- First, ask your partner to review and give you feedback for this project then mention me again on this project.

**Comment by Fikrat2002** [comment]
> @ahzamir 
> 
> linters issues solved, kindly check it out

@far_faqiri kindly check out my project as the linters issue is solved

**Comment by ahzamir** [comment]
> > @ahzamir
> > linters issues solved, kindly check it out
> 
> @far_faqiri kindly check out my project as the linters issue is solved

@Fikrat2002 

You used the wrong username for mentioning your partner

**Comment by faridafaqiri** [comment]
Hi @Fikrat2002 🙋‍♀,

Great job! 💯 You've nailed all the project requirements👏Your feature is complete! Congratulations!!! 🎊🏆

Status: Need changes
Note: A tiny change is required📍

Highlights 🌞
🏆 Successfully implemented a great design
✅ Created a professional repository with your project name
✅ Passed FreeCodeCamp requirements for the project
✅ Used Gitflow correctly by creating a development branch, setting it as default, and making commits on your feature branch
✅ Wrote meaningful commit messages
✅ Set up appropriate linter configurations based on your project's language
✅ No linter errors!
✅ Followed the task and used command-line commits
✅ Submitted a pull request from your feature branch to the development branch and shared the link for review
✅ Provided a clear and detailed description of your work in the PR
✅ Created a professional README.md file in your repository
✅ The project is responsive
❌ Maintained clean code

**Comment by faridafaqiri** [comment]
@Fikrat2002 
your html code is not clean some opening tag instead of starting 2 spaces starting with 4 space kindly check it.

**Comment by Fikrat2002** [comment]
> @Fikrat2002 your html code is not clean some opening tag instead of starting 2 spaces starting with 4 space kindly check it.

@faridafaqiri html codes cleaned kindly check it out

**Comment by faridafaqiri** [comment]
@Fikrat2002 Hi!
status: Approved✔️
Great job! 💯 Your feature is complete! Congratulations!!! 🎊🏆
Highlights 🌞
🎉 Great Design Implemented
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly 
✔️ No linter errors 
✔️ You have followed the Palindrome Checker project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️Your design is responsive

**Comment by Fikrat2002** [comment]
> @Fikrat2002 
> 
> your html code is not clean some opening tag instead of starting 2 spaces starting with 4 space kindly check it. 

@ahzamir The project is approved by @faridafaqiri waiting for your review

**Review by ahzamir — APPROVED** [review]
### Hi @Fikrat2002 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Palindrome Checker project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
